### ISSUE TITLE
Revamp 'For Virtual Space Owners' Section

### ISSUE THREAD

**Issue by philburrrt** [zestymarket/docs#6]
Zesty is looking for someone to improve the details/flow of the onboarding docs. This involves guides on how to implement Zesty banners into various WebXR engines, MMO metaverses, etc.

I'd like to work on this for 2 weeks and am requesting $1250 upon completion.

Here is some of my work for reference: 
https://docs.yearn.finance/ (revised entire gitbook docs then migrated everything to docusaurus)
https://substrata-docs.vercel.app/ (current project)

**Comment by limbofeather** [comment]
Signing off on this to confirm task!

**Comment by limbofeather** [comment]
@philburrrt which address should we send usdc to?

**Comment by philburrrt** [comment]
@limbofeather 0x1963203759f5c5eb5c5c916b3509c9f26dd0381a ~ thanks

**Comment by limbofeather** [comment]
@philburrrt sent: 0x4e3f6bcf104a81fa28c3f0d0bddb6b6ad96dbdbb4d6a86a7af5bd37c558ed89c

Want to work on the same thing for advertisers?

**Comment by philburrrt** [comment]
@limbofeather Appreciate it!
Yeah I'm willing to do anything up to a complete revision, update and migration off of GitBooks and onto something else if you're interested. 

For now, I'll put a 1 week timeframe on the advertisers section & request $250?

It might be easier to figure out fair cost if we do something a bit larger scale. just lmk

**Comment by limbofeather** [comment]
@philburrrt that works, let's do it.

**Comment by limbofeather** [comment]
Closing with tx: https://etherscan.io/tx/0x4e3f6bcf104a81fa28c3f0d0bddb6b6ad96dbdbb4d6a86a7af5bd37c558ed89c
